export const REPAIR_STATUSES = [
  "pending",
  "reviewing",
  "contacted",
  "device_received",
  "diagnosis",
  "quote_sent",
  "customer_approved",
  "repairing",
  "ready",
  "delivered",
  "completed",
  "cancelled",
] as const;

export type RepairStatus = (typeof REPAIR_STATUSES)[number];

export const SELL_STATUSES = [
  "pending",
  "under_review",
  "contacted",
  "price_offered",
  "accepted",
  "rejected",
  "device_received",
  "quality_check",
  "payment_processing",
  "completed",
  "cancelled",
] as const;

export type SellStatus = (typeof SELL_STATUSES)[number];

export const ORDER_STATUSES = [
  "pending",
  "confirmed",
  "processing",
  "shipped",
  "out_for_delivery",
  "delivered",
  "cancelled",
  "refunded",
] as const;

export type OrderStatus = (typeof ORDER_STATUSES)[number];

export const PAYMENT_STATUSES = [
  "pending",
  "paid",
  "failed",
  "refunded",
  "cod_pending",
] as const;

export type PaymentStatus = (typeof PAYMENT_STATUSES)[number];

export const PRODUCT_CONDITIONS = [
  "new",
  "refurbished",
  "used_like_new",
  "used_good",
  "used_fair",
] as const;

export type ProductCondition = (typeof PRODUCT_CONDITIONS)[number];

export const INVENTORY_STATUSES = [
  "in_stock",
  "reserved",
  "sold",
  "damaged",
  "returned",
] as const;

export type InventoryStatus = (typeof INVENTORY_STATUSES)[number];

export const STATUS_LABELS: Record<string, string> = {
  pending: "Pending",
  reviewing: "Reviewing",
  contacted: "Contacted",
  device_received: "Device Received",
  diagnosis: "Diagnosis",
  quote_sent: "Quote Sent",
  customer_approved: "Customer Approved",
  repairing: "Repairing",
  ready: "Ready for Pickup",
  delivered: "Delivered",
  completed: "Completed",
  cancelled: "Cancelled",
  under_review: "Under Review",
  price_offered: "Price Offered",
  accepted: "Accepted",
  rejected: "Rejected",
  quality_check: "Quality Check",
  payment_processing: "Payment Processing",
  confirmed: "Confirmed",
  processing: "Processing",
  shipped: "Shipped",
  out_for_delivery: "Out for Delivery",
  refunded: "Refunded",
  paid: "Paid",
  failed: "Failed",
  cod_pending: "COD Pending",
  new: "Brand New",
  refurbished: "Refurbished",
  used_like_new: "Used — Like New",
  used_good: "Used — Good",
  used_fair: "Used — Fair",
  in_stock: "In Stock",
  reserved: "Reserved",
  sold: "Sold",
  damaged: "Damaged",
  returned: "Returned",
};

/** Maps status → badge color token class */
export const STATUS_COLORS: Record<string, string> = {
  pending: "bg-[#FFF7ED] text-[#C2410C] border-[#FFEDD5]",
  reviewing: "bg-[#F5F3FF] text-[#6D28D9] border-[#DDD6FE]",
  under_review: "bg-[#F5F3FF] text-[#6D28D9] border-[#DDD6FE]",
  contacted: "bg-[#F0FDFA] text-[#0F766E] border-[#CCFBF1]",
  device_received: "bg-[#F0FDFA] text-[#0F766E] border-[#CCFBF1]",
  diagnosis: "bg-[#F5F3FF] text-[#6D28D9] border-[#DDD6FE]",
  quote_sent: "bg-[#FFF7ED] text-[#C2410C] border-[#FFEDD5]",
  price_offered: "bg-[#FFF7ED] text-[#C2410C] border-[#FFEDD5]",
  customer_approved: "bg-[#F0FDFA] text-[#0F766E] border-[#CCFBF1]",
  accepted: "bg-[#F0FDFA] text-[#0F766E] border-[#CCFBF1]",
  repairing: "bg-[#FFF7ED] text-[#C2410C] border-[#FFEDD5]",
  quality_check: "bg-[#F0FDFA] text-[#0F766E] border-[#CCFBF1]",
  payment_processing: "bg-[#F0FDFA] text-[#0F766E] border-[#CCFBF1]",
  ready: "bg-[#F5F3FF] text-[#6D28D9] border-[#DDD6FE]",
  delivered: "bg-[#F0FDFA] text-[#0F766E] border-[#CCFBF1]",
  completed: "bg-[#F0FDFA] text-[#0F766E] border-[#CCFBF1]",
  cancelled: "bg-[#FEF2F2] text-[#B91C1C] border-[#FECACA]",
  rejected: "bg-[#FEF2F2] text-[#B91C1C] border-[#FECACA]",
  confirmed: "bg-[#FFF7ED] text-[#C2410C] border-[#FFEDD5]",
  processing: "bg-[#FFF7ED] text-[#C2410C] border-[#FFEDD5]",
  shipped: "bg-[#F0FDFA] text-[#0F766E] border-[#CCFBF1]",
  out_for_delivery: "bg-[#F5F3FF] text-[#6D28D9] border-[#DDD6FE]",
  refunded: "bg-[#F1F5F9] text-[#475569] border-[#E2E8F0]",
  paid: "bg-[#F0FDFA] text-[#0F766E] border-[#CCFBF1]",
  failed: "bg-[#FEF2F2] text-[#B91C1C] border-[#FECACA]",
  cod_pending: "bg-[#FFF7ED] text-[#C2410C] border-[#FFEDD5]",
  in_stock: "bg-[#F0FDFA] text-[#0F766E] border-[#CCFBF1]",
  low_stock: "bg-[#FFF7ED] text-[#C2410C] border-[#FFEDD5]",
  out_of_stock: "bg-[#FEF2F2] text-[#B91C1C] border-[#FECACA]",
};

export const PHONE_BRANDS = [
  "Apple",
  "Apple Mac",
  "Samsung",
  "Xiaomi",
  "OnePlus",
  "Vivo",
  "Oppo",
  "Realme",
  "Google",
  "Nothing",
  "Motorola",
  "Nokia",
  "Other",
] as const;

export const STORAGE_OPTIONS = ["32GB", "64GB", "128GB", "256GB", "512GB", "1TB"] as const;
export const RAM_OPTIONS = ["2GB", "3GB", "4GB", "6GB", "8GB", "12GB", "16GB"] as const;

export const PHONE_COLORS = [
  "Black",
  "White",
  "Silver",
  "Gold",
  "Blue",
  "Green",
  "Red",
  "Purple",
  "Pink",
  "Graphite",
  "Space Gray",
  "Midnight",
  "Starlight",
  "Rose Gold",
  "Natural Titanium",
  "Blue Titanium",
  "Black Titanium",
  "White Titanium",
  "Desert Titanium",
  "Mint",
  "Lavender",
  "Yellow",
  "Orange",
  "Cream",
  "Brown",
  "Other",
] as const;

export const PHONE_MODELS_BY_BRAND: Record<(typeof PHONE_BRANDS)[number], readonly string[]> = {
  Apple: [
    "iPhone 16 Pro Max",
    "iPhone 16 Pro",
    "iPhone 16 Plus",
    "iPhone 16",
    "iPhone 15 Pro Max",
    "iPhone 15 Pro",
    "iPhone 15 Plus",
    "iPhone 15",
    "iPhone 14 Pro Max",
    "iPhone 14 Pro",
    "iPhone 14 Plus",
    "iPhone 14",
    "iPhone 13",
    "iPhone 12",
    "iPhone SE",
    'MacBook Pro 16" (M3/M2/M1)',
    'MacBook Pro 14" (M3/M2/M1)',
    'MacBook Air 15" (M3/M2)',
    'MacBook Air 13" (M3/M2/M1)',
    "Other iPhone / Mac",
  ],
  "Apple Mac": [
    'MacBook Pro 16" (M3 Max / M3 Pro / M2 / M1)',
    'MacBook Pro 14" (M3 Max / M3 Pro / M2 / M1)',
    'MacBook Pro 13" (M2 / M1 / Intel)',
    'MacBook Air 15" (M3 / M2)',
    'MacBook Air 13" (M3 / M2 / M1)',
    "MacBook Air (Intel)",
    'MacBook Pro 15" / 16" (Intel)',
    'iMac 24" (M3 / M1)',
    "iMac 27\" Retina",
    "Mac mini (M2 / M1 / Intel)",
    "Mac Studio (M2 / M1)",
    "Mac Pro",
    "Other Mac Model",
  ],
  Samsung: [
    "Galaxy S24 Ultra",
    "Galaxy S24+",
    "Galaxy S24",
    "Galaxy S23 Ultra",
    "Galaxy S23+",
    "Galaxy S23",
    "Galaxy S22 Ultra",
    "Galaxy S22",
    "Galaxy Z Fold6",
    "Galaxy Z Fold5",
    "Galaxy Z Flip6",
    "Galaxy Z Flip5",
    "Galaxy A55",
    "Galaxy A54",
    "Galaxy A35",
    "Galaxy A15",
    "Other",
  ],
  Xiaomi: [
    "Xiaomi 14 Ultra",
    "Xiaomi 14",
    "Xiaomi 13 Pro",
    "Xiaomi 13",
    "Redmi Note 13 Pro+",
    "Redmi Note 13 Pro",
    "Redmi Note 13",
    "Redmi Note 12 Pro",
    "Redmi 13C",
    "POCO X6 Pro",
    "POCO F6",
    "Other",
  ],
  OnePlus: [
    "OnePlus 12",
    "OnePlus 12R",
    "OnePlus 11",
    "OnePlus Nord 4",
    "OnePlus Nord CE 4",
    "OnePlus Nord CE 3",
    "OnePlus Open",
    "Other",
  ],
  Vivo: [
    "Vivo X100 Pro",
    "Vivo X100",
    "Vivo V30 Pro",
    "Vivo V30",
    "Vivo V29",
    "Vivo Y100",
    "Vivo Y28",
    "iQOO 12",
    "iQOO Neo 9 Pro",
    "Other",
  ],
  Oppo: [
    "Oppo Find X7 Ultra",
    "Oppo Find X6 Pro",
    "Oppo Reno 12 Pro",
    "Oppo Reno 11 Pro",
    "Oppo Reno 11",
    "Oppo A79",
    "Oppo A58",
    "Other",
  ],
  Realme: [
    "Realme GT 6",
    "Realme GT 5 Pro",
    "Realme 12 Pro+",
    "Realme 12 Pro",
    "Realme 11 Pro+",
    "Realme Narzo 70 Pro",
    "Realme C67",
    "Other",
  ],
  Google: [
    "Pixel 9 Pro XL",
    "Pixel 9 Pro",
    "Pixel 9",
    "Pixel 8 Pro",
    "Pixel 8",
    "Pixel 8a",
    "Pixel 7 Pro",
    "Pixel 7a",
    "Pixel Fold",
    "Other",
  ],
  Nothing: ["Nothing Phone (2a) Plus", "Nothing Phone (2a)", "Nothing Phone (2)", "Nothing Phone (1)", "Other"],
  Motorola: [
    "Motorola Edge 50 Ultra",
    "Motorola Edge 50 Pro",
    "Motorola Edge 40 Neo",
    "Moto G85",
    "Moto G64",
    "Moto G34",
    "Other",
  ],
  Nokia: ["Nokia G42", "Nokia G22", "Nokia C32", "Nokia XR21", "Other"],
  Other: ["Other"],
};

export const LAPTOP_BRANDS = [
  "Apple (MacBook / iMac)",
  "Dell",
  "HP",
  "Lenovo",
  "ASUS",
  "Acer",
  "MSI",
  "Microsoft Surface",
  "Samsung Galaxy Book",
  "Razer",
  "LG Gram",
  "Other Laptop",
] as const;

export const LAPTOP_STORAGE_OPTIONS = ["256GB SSD", "512GB SSD", "1TB SSD", "2TB SSD", "4TB SSD", "1TB HDD"] as const;
export const LAPTOP_RAM_OPTIONS = ["8GB", "16GB", "24GB", "32GB", "64GB"] as const;

export const LAPTOP_MODELS_BY_BRAND: Record<(typeof LAPTOP_BRANDS)[number], readonly string[]> = {
  "Apple (MacBook / iMac)": [
    'MacBook Pro 16" (M3 Max / M3 Pro / M2 / M1)',
    'MacBook Pro 14" (M3 Max / M3 Pro / M2 / M1)',
    'MacBook Pro 13" (M2 / M1 / Intel)',
    'MacBook Air 15" (M3 / M2)',
    'MacBook Air 13" (M3 / M2 / M1)',
    "MacBook Air (Intel)",
    'MacBook Pro 15" / 16" (Intel)',
    'iMac 24" (M3 / M1)',
    'iMac 27" Retina',
    "Mac mini (M2 / M1 / Intel)",
    "Mac Studio / Mac Pro",
    "Other Mac Model",
  ],
  Dell: [
    "XPS 16 / 15",
    "XPS 13 / 13 Plus",
    "Inspiron 15 / 16",
    "Inspiron 14 2-in-1",
    "Latitude 7440 / 5440",
    "Alienware m16 / m18 / x16",
    "Dell G15 / G16 Gaming",
    "Vostro 3520 / 5630",
    "Other Dell Model",
  ],
  HP: [
    "HP Pavilion 15 / 14",
    "HP Pavilion Plus 14",
    "HP Spectre x360 14 / 16",
    "HP Envy x360 15 / 14",
    "HP OMEN 16 / 17",
    "HP Victus 15 / 16",
    "HP EliteBook 840 / 845",
    "HP ProBook 450 / 440",
    "Other HP Model",
  ],
  Lenovo: [
    "ThinkPad X1 Carbon Gen 11/12",
    "ThinkPad T14 / T16",
    "ThinkPad E14 / E16",
    "IdeaPad Slim 5 / 3",
    "Yoga 9i / 7i / 6",
    "Legion Pro 7i / 5i",
    "Lenovo LOQ 15 / 16",
    "ThinkBook 14 / 15",
    "Other Lenovo Model",
  ],
  ASUS: [
    "ROG Zephyrus G16 / G14",
    "ROG Strix G16 / SCAR 18",
    "ASUS TUF Gaming F15 / A15",
    "Zenbook 14 OLED / Duo",
    "Vivobook 15 / 16 / Pro",
    "ExpertBook B9 / B5",
    "Other ASUS Model",
  ],
  Acer: [
    "Nitro 5 / Nitro V 15",
    "Predator Helios 16 / 18",
    "Swift Go 14 / Swift 3",
    "Aspire 5 / Aspire 3",
    "Acer Spin 5 / 3",
    "Other Acer Model",
  ],
  MSI: [
    "MSI Stealth 16 / 14 Studio",
    "MSI Raider GE78 / GE68",
    "MSI Cyborg 15 / Thin 15",
    "MSI Katana 15 / 17",
    "MSI Modern 15 / 14",
    "Other MSI Model",
  ],
  "Microsoft Surface": [
    "Surface Laptop 6 / 5",
    "Surface Pro 10 / 9 / 8",
    "Surface Laptop Studio 2",
    "Surface Laptop Go 3",
    "Surface Book 3 / 2",
    "Other Surface Model",
  ],
  "Samsung Galaxy Book": [
    "Galaxy Book4 Ultra",
    "Galaxy Book4 Pro / 360",
    "Galaxy Book4 / Book3 360",
    "Galaxy Book2 Pro",
    "Other Galaxy Book Model",
  ],
  Razer: ["Razer Blade 16", "Razer Blade 18", "Razer Blade 14", "Razer Blade 15", "Other Razer Model"],
  "LG Gram": ['LG Gram 17 / 16"', 'LG Gram SuperSlim 15"', "LG Gram Style / 2-in-1", "Other LG Model"],
  "Other Laptop": ["Other Laptop"],
};

export const COMPANY_DETAILS = {
  legalName: "RAJ KUMAR",
  tradeName: "HMC ENTERPRISES",
  brandName: "HMC Mobile",
  registrationNumber: "06EFBPK5242G1ZO",
  address: {
    line1: "Shop No, ALG-II, Pushpa Complex",
    city: "Hisar",
    state: "Haryana",
    pincode: "125001",
    full: "Shop No, ALG-II, Pushpa Complex, Hisar, Haryana – 125001",
  },
  phone: "8130155540",
  formattedPhone: "+91 81301 55540",
  whatsappNumber: "918130155540",
  whatsappLink: "https://wa.me/918130155540",
  email: "hello@hmcmobile.in",
  hours: "Mon – Sat: 10:00 AM – 8:00 PM · Sun: 11:00 AM – 5:00 PM",
} as const;
